service: lambda-typescript
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs14.x
    region: ${opt:region, 'eu-north-1'}
    stage: ${opt:stage, 'dev'}

    environment:
        envMessage: This is env message

functions:
    helloName:
        handler: src/index.helloName
        events:
            - httpApi:
                  path: /helloName
                  method: post

plugins:
    - serverless-webpack
